version = "1.0"
start_date = '2009-01-01' # Start date for all the computations
ref_symbol = 'ETFMIB.MI' # Symbol used to map main market (SPY, ETFMIB,...)
test_portfolio = ['STS.MI', 'ENEL.MI', 'SFER.MI']
ftsemib_symbols = ['A2A.MI', 'ATL.MI', 'BMPS.MI', 'BAMI.MI',
 'BMED.MI', 'BPE.MI',
 'BRE.MI', 'BZU.MI', 'CPR.MI', 'CNHI.MI', 'ENEL.MI', 'ENI.MI',
 'EXO.MI', 'SFER.MI', 'RACE.MI', 'FCA.MI', 'FBK.MI', 'G.MI',
 'ISP.MI', 'IG.MI', 'LDO.MI', 'LUX.MI', 'MS.MI', 'MB.MI',
 'MONC.MI', 'PST.MI', 'PRY.MI', 'REC.MI', 'SPM.MI', 'SRG.MI',
 'STM.MI', 'TIT.MI', 'TEN.MI', 'TRN.MI', 'UBI.MI', 'UCG.MI',
 'UNI.MI', 'US.MI', 'YNAP.MI']
ftsemib_allshare_symbols = ['A2A.MI', 'ACE.MI', 'ACO.MI',
 'ACS.MI', 'AE.MI', 'AEF.MI',
 'ADB.MI', 'ARN.MI', 'AZA.MI', 'ATH.MI', 'AMP.MI', 'ANIM.MI',
 'STS.MI', 'ASR.MI', 'ASC.MI', 'AST.MI', 'AT.MI', 'ATL.MI',
 'AGL.MI', 'AUTME.MI', 'AZM.MI', 'BEC.MI', 'CRG.MI', 'CRGR.MI',
 'BFE.MI', 'BGN.MI', 'IF.MI', 'BMPS.MI', 'PRO.MI', 'BST.MI',
 'BAMI.MI', 'SANT.MI', 'BANZ.MI', 'BAN.MI', 'B.MI', 'BB.MI',
 'BIM.MI', 'BMED.MI', 'PEL.MI', 'BPSO.MI', 'SPO.MI', 'BDBR.MI',
 'BDB.MI', 'BSRP.MI', 'BET.MI', 'BE.MI', 'BNS.MI', 'BEST.MI',
 'BIA.MI', 'BCM.MI', 'BSS.MI', 'BIE.MI', 'BOE.MI', 'BF.MI',
 'BO.MI', 'BOR.MI', 'BPE.MI', 'BRE.MI', 'BRI.MI', 'BC.MI',
 'BZU.MI', 'BZUR.MI', 'CAD.MI', 'CAI.MI', 'CLF.MI', 'CALT.MI',
 'CED.MI', 'CPR.MI', 'CARR.MI', 'CASS.MI', 'CMB.MI', 'CEM.MI',
 'CLT.MI', 'RIC.MI', 'CERV.MI', 'CHL.MI', 'CIA.MI', 'CC.MI',
 'CIR.MI', 'CLE.MI', 'CNHI.MI', 'COF.MI', 'CRES.MI', 'CNP.MI',
 'CVAL.MI', 'CE.MI', 'CSP.MI', 'CTIC.MI', 'DA.MI', 'DMN.MI',
 'DIS.MI', 'DAN.MI', 'DANR.MI', 'DAL.MI', 'DLG.MI', 'DEA.MI',
 'DIA.MI', 'DIB.MI', 'DMA.MI', 'EDNR.MI', 'EEMS.MI', 'EIT.MI',
 'ELN.MI', 'ELC.MI', 'EM.MI', 'ENAV.MI', 'ENAV_D.MI', 'ENEL.MI',
 'ENV.MI', 'ENI.MI', 'ERG.MI', 'PRT.MI', 'EUK.MI', 'ETH.MI',
 'EXO.MI', 'XPR.MI', 'FKR.MI', 'SFER.MI', 'RACE.MI', 'FCA.MI',
 'FDA.MI', 'FM.MI', 'FILA.MI', 'FCT.MI', 'FCT_D.MI', 'FBK.MI',
 'FNM.MI', 'FUL.MI', 'GAB.MI', 'GSP.MI', 'GE.MI', 'G.MI',
 'GEO.MI', 'GEQ.MI', 'ES.MI', 'WIG.MI', 'IGV.MI', 'GCN.MI',
 'HER.MI', 'IMA.MI', 'IGD.MI', 'S24.MI', 'IMS.MI', 'IIN.MI',
 'IKG.MI', 'IKGR.MI', 'IP.MI', 'ISP.MI', 'ISPR.MI', 'INW.MI',
 'IRC.MI', 'IRE.MI', 'ISGS.MI', 'ISG.MI', 'ITW.MI', 'IG.MI',
 'IOL.MI', 'ITM.MI', 'IVS.MI', 'JUVE.MI', 'KRE.MI', 'LD.MI',
 'LR.MI', 'LDO.MI', 'LUX.MI', 'LVEN.MI', 'MT.MI', 'MARR.MI',
 'MZB.MI', 'MCH.MI', 'MS.MI', 'MB.MI', 'MIT.MI', 'MSK.MI',
 'MLM.MI', 'MONC.MI', 'MN.MI', 'MTV.MI', 'MON.MI', 'MOL.MI',
 'NICE.MI', 'NR.MI', 'OLI.MI', 'OJM.MI', 'OVS.MI', 'PAN.MI',
 'PLT.MI', 'PIA.MI', 'PRL.MI', 'PINF.MI', 'PQ.MI', 'PSF.MI',
 'POL.MI', 'PST_D.MI', 'PST.MI', 'PRS.MI', 'PR.MI', 'PRI.MI',
 'PRY.MI', 'RWAY.MI', 'RWAY_D.MI', 'RAT.MI', 'RCS.MI', 'REC.MI',
 'RM.MI', 'REY.MI', 'LIT.MI', 'RN.MI', 'ROS.MI', 'SSL.MI',
 'SAB.MI', 'SG.MI', 'SGR.MI', 'SFL.MI', 'SPM.MI', 'SALR.MI',
 'SAL.MI', 'SRS.MI', 'SAVE.MI', 'SRI.MI', 'SES.MI', 'SIS.MI',
 'SII.MI', 'SNA.MI', 'SRG.MI', 'SO.MI', 'SOL.MI', 'STEF.MI',
 'STM.MI', 'TIP.MI', 'TAS.MI', 'TGYM.MI', 'TECN.MI', 'TIT.MI',
 'TITR.MI', 'TEN.MI', 'TRN.MI', 'TER.MI', 'TES.MI', 'TIS.MI',
 'TOD.MI', 'TYA.MI', 'TFI.MI', 'TXT.MI', 'UBI.MI', 'UCG.MI',
 'UCGR.MI', 'UNI.MI', 'US.MI', 'VLS.MI', 'VIA.MI', 'VAS.MI',
 'YNAP.MI', 'ZV.MI', 'ZUC.MI', 'ZUCR.MI']
